#!/bin/bash

# pegando o uptime do servidor
upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

# pegando o load averages dos proc
read one five fifteen rest < /proc/loadavg

# demora muito para ler o ip
# IP Addresses.......: `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/`

# modelo de CPU
# cat /proc/cpuinfo |grep 'model name' |awk -F ":" '{print substr($2,2,300)}'
# cat /proc/cpuinfo |grep 'model name' |awk -F ":" '{print substr($2,2,300)}' |sed -n -e 1p

#echo -e "\033[93m"
#echo "IPs"
#ip addr show |grep inet |awk '{print $2}' |sed -n -e 3,8p

echo -e "
\033[34m
                                    BLUE3 INTERNET
 ____  _            ____            `date +"%A, %e %B %Y, %R:%S"`
|  _ \| |          |___ \\           `uname -srmo `$(tput setaf 1)
| |_) | |_   _  ___  __) |
|  _ <| | | | |/ _ \|__ <           Uptime.............: ${UPTIME}
| |_) | | |_| |  __/___) |          Memory.............: `cat /proc/meminfo |grep MemFree |awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total)
|____/|_|\__,_|\___|____/           CPU Info...........: `cat /proc/cpuinfo |grep 'model name' |awk -F ":" '{print substr($2,2,300)}' |sed -n -e 1p`
                                    CPU Load...........: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
                                    
\033[97m
"
#				    Running Processes..: `ps ax | wc -l | tr -d " "`
#                                   IP Addresses IPv4..: `ip addr show |grep inet |awk '{print $2}' |sed -n -e 3,3p`
#                                   IP Addresses.IPv6..: `ip addr show |grep inet |awk '{print $2}' |sed -n -e 4,4p`
#				    IP Addresses Pub...: `curl -s "https://ifconfig.me/ip"`
#
#				    Time Zone..........: `curl ipinfo.io/timezone`
#				    Local..............: `curl ipinfo.io/city`
#				    Organization.......: `curl -s "https://ipinfo.io/org" |awk '{print $2,$3}'`
#				    ASN................: `curl -s "https://ipinfo.io/org" |awk '{print $1}'`
#for i in {16..21} {21..16} ; do echo -en "\e[38;5;${i}m  B3  \e[0m" ; done ; echo
for i in {16..21} {21..16} ; do echo -en "\e[48;5;${i}m     \e[0m" ; done ; echo ; echo 
