#!/bin/bash

# Garante ambiente mínimo
export TERM=${TERM:-xterm-256color}

# Função segura para cores
color() {
    tput setaf "$1" 2>/dev/null || true
}

# uptime
upSeconds="$(cut -d. -f1 /proc/uptime)"
secs=$((upSeconds%60))
mins=$((upSeconds/60%60))
hours=$((upSeconds/3600%24))
days=$((upSeconds/86400))
UPTIME=$(printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs")

# load
read one five fifteen _ < /proc/loadavg

# cores
blue="\033[34m"
white="\033[97m"
red=$(color 1)

echo -e "
${blue}
                                    BLUE3 INTERNET
 ____  _            ____            $(date +"%A, %e %B %Y, %R:%S")
|  _ \| |          |___ \\           $(uname -srmo)
| |_) | |_   _  ___  __) |
|  _ <| | | | |/ _ \|__ <           Uptime.............: ${UPTIME}
| |_) | | |_| |  __/___) |          Memory.............: $(awk '/MemFree/ {print $2}' /proc/meminfo)kB (Free) / $(awk '/MemTotal/ {print $2}' /proc/meminfo)kB (Total)
|____/|_|\__,_|\___|____/           CPU Info...........: $(awk -F: '/model name/ {print substr($2,2); exit}' /proc/cpuinfo)
                                    CPU Load...........: ${one}, ${five}, ${fifteen} (1, 5, 15 min)

${white}
"